KETI_renderer:
  width: 500
  height: 500
  near: 1
  far: 600
  fx: 707.106781187
  fy: 707.106781187
  px: 250.0
  py: 250.0
  distx: 0.0
  disty: -0.0
  orig_res: 500
  recon_res: 500
  voxel_size: 500
  cmin: [0, 0, 300]
  cmax: [0, 0, 300]
  view_idx: [0, 360, 360]
  pitch: [0, 1, 1]
  hmin: 180
  hmax: 180
  real_dist: 300.0
  projection: perspective
  # indoor lighting condition
  light_num: 1
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

# use Dell WebCam intrinsic parameters
#Famoz2023_webcam:
#  width: 1024
#  height: 1024
#  near: 1
#  far: 600
#  fx: 1064.77037037
#  fy: 1064.77037037
#  px: 512.0
#  py: 820.0
#  distx: 0.0
#  disty: 0.0
#  real_dist: 220.0
#  orig_res: 1024
#  recon_res: 1024
#  voxel_size: 512
#  cmin: [ 0, 60, 220 ]
#  cmax: [ 0, 60, 220 ]
#  hmin: 170
#  hmax: 170
#  view_idx: [0]
#  projection: perspective
#  # indoor lighting condition
#  light_direction: [0, -0.7, -1]
#  light_intensity_ambient: 0.8
#  light_intensity_directional: 0.5
#  light_intensity_ambient: 0.8
#  light_intensity_directional: 0.5
