Famoz2023_gt:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 532.385185185
  fy: 532.385185185
  px: 256.0
  py: 410.0
  distx: 0.0
  disty: -0.0
  cmin: [0, 60, 220]
  cmax: [0, 60, 220]
  view_idx: [0, 1, 2, 3, 5, 10, 350, 355, 357, 358, 359]
  pitch: [0]
  hmin: 170
  hmax: 170
  projection: perspective
  # indoor lighting condition
  light_num: 30
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

# to generate uniformly sampled images.
Famoz2023_360:
  width: 1024
  height: 1024
  near: 1
  far: 600
  fx: 1064.757751019
  fy: 1064.757751019
  px: 512.0
  py: 512.0
  distx: 0.0
  disty: 0.0
  cmin: 220
  cmax: 220
  real_dist: 220.0
  view_idx: [0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]
#  view_idx_h: [30]
  projection: perspective
  # indoor lighting condition
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

Famoz2023_inference:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 532.385185185
  fy: 532.385185185
  px: 256.0
  py: 410.0
  distx: 0.0
  disty: 0.0
  real_dist: 220.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [ 0, 300, 500 ]
  cmax: [ 0, 300, 500 ]
  hmin: 170
  hmax: 170
  view_idx: [0]
  projection: perspective
  # indoor lighting condition
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

KETI_CVPR2024_MVIEW:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 724.0773439350247
  fy: 724.0773439350247
  px: 256.0
  py: 256.0
  distx: 0.0
  disty: 0.0
  real_dist: 300.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [ 0, 0, 300 ]
  cmax: [ 0, 0, 300 ]
  hmin: 180
  hmax: 180
  view_idx: [0, 5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 110, 120, 125, 130, 135, 140, 150, 160, 170, 175, 180, 190, 200, 210, 220, 230, 240, 245, 250, 255, 260, 270, 280, 285, 290, 300, 310, 320, 330, 335, 340, 345, 350, 355]
  projection: perspective
  # indoor lighting condition
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

KETI_CVPR2024_gt:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 724.0773439350247
  fy: 724.0773439350247
  px: 256.0
  py: 256.0
  distx: 0.0
  disty: 0.0
  real_dist: 300.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [ 0, 0, 300 ]
  cmax: [ 0, 0, 300 ]
  hmin: 180
  hmax: 180
  view_idx: [0, 1, 2, 3, 5, 10, 350, 355, 357, 358, 359]
  projection: perspective
  # indoor lighting condition
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

KETI_CVPR2024:  # inference
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 724.0773439350247
  fy: 724.0773439350247
  px: 256.0
  py: 256.0
  distx: 0.0
  disty: 0.0
  real_dist: 300.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [ 0, 0, 300 ]
  cmax: [ 0, 0, 300 ]
  hmin: 180
  hmax: 180
  view_idx: [0]
  projection: perspective
  # indoor lighting condition
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

KETI_renderer:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 724.077343935
  fy: 724.077343935
  px: 256.0
  py: 256.0
  distx: 0.0
  disty: -0.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [0, 0, 300]
  cmax: [0, 0, 300]
  view_idx: [0, 360, 1]
  pitch: [-45, 45, 5]
  hmin: 180
  hmax: 180
  real_dist: 300.0
  projection: perspective
  # indoor lighting condition
  light_num: 1
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

KETI_CVPR2024:
  width: 512
  height: 512
  near: 1
  far: 600
  fx: 724.077343935
  fy: 724.077343935
  px: 256.0
  py: 256.0
  distx: 0.0
  disty: -0.0
  real_dist: 300.0
  orig_res: 512
  recon_res: 512
  voxel_size: 512
  cmin: [0, 0, 300]
  cmax: [0, 0, 300]
  view_idx: [350, 355, 357, 358, 359, 0, 1, 2, 3, 5, 10]
  pitch: [0]
  hmin: 180
  hmax: 180
  projection: perspective
  # indoor lighting condition
  light_num: 1
  light_direction: [0, -0.7, -1]
  light_intensity_ambient: 0.8
  light_intensity_directional: 0.5

# CVPR2023_renderer:
#   width: 512
#   height: 512
#   near: 1
#   far: 600
#   fx: 724.077343935
#   fy: 724.077343935
#   px: 256.0
#   py: 256.0
#   distx: 0.0
#   disty: -0.0
#   real_dist: 300.0
#   orig_res: 512
#   recon_res: 512
#   voxel_size: 512
#   cmin: [0, 0, 300]
#   cmax: [0, 0, 300]
#   view_idx: [350, 355, 357, 358, 359, 0, 1, 2, 3, 5, 10]
#   pitch: [0]
#   hmin: 180
#   hmax: 180
#   projection: perspective
#   # indoor lighting condition
#   light_num: 30
#   light_direction: [0, -0.7, -1]
#   light_intensity_ambient: 0.8
#   light_intensity_directional: 0.5

# use Dell WebCam intrinsic parameters
#Famoz2023_webcam:
#  width: 512
#  height: 512
#  near: 1
#  far: 600
#  fx: 532.385185185
#  fy: 532.385185185
#  px: 256.0
#  py: 410.0
#  distx: 0.0
#  disty: 0.0
#  real_dist: 220.0
#  orig_res: 512
#  recon_res: 512
#  voxel_size: 512
#  cmin: [ 0, 60, 220 ]
#  cmax: [ 0, 60, 220 ]
#  hmin: 170
#  hmax: 170
#  view_idx: [0]
#  projection: perspective
#  # indoor lighting condition
#  light_direction: [0, -0.7, -1]
#  light_intensity_ambient: 0.8
#  light_intensity_directional: 0.5
#  light_intensity_ambient: 0.8
#  light_intensity_directional: 0.5
